version: '3.4'

services:
  usedcardealerwebmvc:
    image: ${DOCKER_REGISTRY-}usedcardealerwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
  usedcardealerpublicapi:
    image: ${DOCKER_REGISTRY-}usedcardealerpublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile