version: '3.4'

services:
  usedcardealerwebmvc:
    image: ${DOCKER_REGISTRY-}usedcardealerwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - "sqlserver"
  usedcardealerpublicapi:
    image: ${DOCKER_REGISTRY-}usedcardealerpublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y

